### PR TITLE
Add AS4242421830 peering at CGK1

### PR DESCRIPTION
**Pull request by atriwidada**

### CODE REVIEW

**Review by jvoss — APPROVED** [review]

**Comment by yzguy** [comment]
Hello,

We have started the deployment of new configuration on our side for the peering at our CGK1 PoP.
It is ready for the configuration on your side.

You can find the relevant information for this PoP on our Nodes page: https://dn42.routedbits.com/nodes/#cgk1
It can also be obtained programmatically via [nodes.json](https://dn42.routedbits.com/nodes.json)

We manage configuration via our dn42-peers repository, you can submit pull requests to add/remove/change your own peerings. Once accepted and merged, the changes are pushed to our routers within a few minutes.

Pull Request: https://github.com/routedbits/dn42-peers/pull/202

Let us know if you have any questions or issues.

Thanks,
NOC, RoutedBits

**Comment by atriwidada** [comment]
Hello,

Wireguard seems connected ok (at least partially). can ping6 fe80::207. can't ping 172.20.19.66. BGP has not established yet.
Backgroud info: I tried to peers with 2 sites, both connected via one wireguard instance. BGP to other site seems ok.

**Comment by jvoss** [comment]
Hi,

You selected IPv4 extended next-hop.  You should not expect to be able to ping IPv4 destinations without BGP providing you with a route for `172.20.19.66` (and an associated IPv6 next-hop address, in this case `fe80::207`).

It appears your side is sending a reset when we attempt to open a BGP session with you:
```
Oct 16 01:24:36 router.cgk1 bgpd[1138]: [H4B4J-DCW2R][EC 33554455] fe80::6060 [Error] bgp_read_packet error: Connection reset by peer
```

Can you verify your BGP configuration for this peering?

**Comment by atriwidada** [comment]
not sure what else to check/reconfigure

wg
interface: dn42
  public key: jE4tRDgVIKLpsuAQqDTeYnOkXWtB19rg/Fkube/UEg8=
  private key: (hidden)
  listening port: 52345

peer: NyDLBU8swSAVZPficE7YhvJw0/KqJi43bwVfaxdgKW0=
  endpoint: 172.232.224.163:51830
  allowed ips: 172.20.15.56/29, 172.20.19.64/27, fdb1:e72a:343d::/48, fe80::207/128, 172.16.0.0/12, 10.0.0.0/8, fd00::/8, fe80::/10
  latest handshake: 32 seconds ago
  transfer: 89.12 KiB received, 50.88 KiB sent
  persistent keepalive: every 2 minutes
  
# /etc/bird/peers/routedbits.conf
# ref: https://mk16.de/blog/dn42-beginner-tips/
#protocol bgp routedbits from dnpeers {
#    neighbor 172.20.19.66 as 4242420207;   
#}

protocol bgp routedbits_v6 from dnpeers {
    neighbor fe80::207%dn42 as 4242420207;
    enable extended messages on;
    graceful restart on;
    long lived graceful restart on;
    interpret communities on;
    prefer older on;
    # syntax error
    #extended next hop on;
}

birdcl show protocols routedbits_v6
BIRD 2.0.12 ready.
Name       Proto      Table      State  Since         Info
routedbits_v6 BGP        ---        start  09:24:11.008  Idle  

no firewall

**Comment by atriwidada** [comment]
seems that I have to run separate wireguard session for each peer. will need to change listening port to 52346 for connection to routedbits

**Comment by jvoss** [comment]
> ```
> # /etc/bird/peers/routedbits.conf
> # ref: https://mk16.de/blog/dn42-beginner-tips/
> #protocol bgp routedbits from dnpeers {
> #    neighbor 172.20.19.66 as 4242420207;   
> #}
> 
> protocol bgp routedbits_v6 from dnpeers {
>     neighbor fe80::207%dn42 as 4242420207;
>     enable extended messages on;
>     graceful restart on;
>     long lived graceful restart on;
>     interpret communities on;
>     prefer older on;
>     # syntax error
>     #extended next hop on;
> }
> ```

This is not the complete BIRD configuration. Where is your template `dnpeers`? 

Without the template defined, you will need to add at a minimum some address families:

```
 protocol bgp routedbits_v6 {
     neighbor fe80::207 as 4242420207;
     interface "dn42";  # NOTE: this should be the wireguard interface configured specifically for RoutedBits
     enable extended messages on;
     graceful restart on;
     long lived graceful restart on;
     interpret communities on;
     prefer older on;
     
     ipv4 {
        extended next hop on;
     };

     ipv6 {           
     };
 }
```

**Comment by atriwidada** [comment]
```
template bgp dnpeers {
    local as OWNAS;
    path metric 1;

    ipv4 {
        import filter {
          if is_valid_network() && !is_self_net() then {
            if (roa_check(dn42_roa, net, bgp_path.last) != ROA_VALID) then {
              # Reject when unknown or invalid according to ROA
              print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
              reject;
            } else accept;
          } else reject;
        };

        export filter { if is_valid_network() && source ~ [RTS_STATIC, RTS_BGP] then accept; else reject; };
        import limit 9000 action block;
    };

    ipv6 {
        import filter {
          if is_valid_network_v6() && !is_self_net_v6() then {
            if (roa_check(dn42_roa_v6, net, bgp_path.last) != ROA_VALID) then {
              # Reject when unknown or invalid according to ROA
              print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
              reject;
            } else accept;
          } else reject;
        };
        export filter { if is_valid_network_v6() && source ~ [RTS_STATIC, RTS_BGP] then accept; else reject; };
        import limit 9000 action block;
    };

   # syntax error
   # extended next hop on;
}

protocol bgp routedbits_v6 from dnpeers {
    # Link-local address of the routedbits node
    neighbor fe80::207%routedbits as 4242420207;
    local fe80::6060 as 4242421830;
    enable extended messages on;
    graceful restart on;
    long lived graceful restart on;
    interpret communities on;
    prefer older on;
    # syntax error
    #extended next hop on;
}

```

I think it's ok now

**Comment by jvoss** [comment]
Excellent.. looks good on our side too:

```
IPv4 Unicast Summary (VRF DN42):
BGP router identifier 172.20.19.66, local AS number 4242420207 vrf-id 4
BGP table version 22914
RIB entries 1361, using 128 KiB of memory
Peers 2, using 40 KiB of memory
Peer groups 4, using 256 bytes of memory
Dampening enabled.

Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
fe80::6060        4 4242421830      1849      1594    22914    0    0 00:10:55          657      674 SARANG

Total number of neighbors 2

IPv6 Unicast Summary (VRF DN42):
BGP router identifier 172.20.19.66, local AS number 4242420207 vrf-id 4
BGP table version 18678
RIB entries 1658, using 155 KiB of memory
Peers 2, using 40 KiB of memory
Peer groups 4, using 256 bytes of memory

Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
fe80::6060        4 4242421830      1849      1594    18678    0    0 00:10:55          728      773 SARANG
```

Glad you got it sorted out. Thanks!

**Comment by atriwidada** [comment]
Thanks so much for your help. My first time setup BGP.

**Pull request merged**
