### PR TITLE
chore: Add AS4242422608 SLIRYA peering at GRU1

### PR DESCRIPTION
**Pull request by yzguy**
Submissions from Google Form

### CODE REVIEW

**Comment by Slirya** [comment]
I've already configured my WireGuard tunnel and BGP client.

**Comment by yzguy** [comment]
@Slirya Did you intend on a Multi-protocol BGP session or separate IPv4 and IPv6 sessions?

We don't see any IPv4 prefixes from you

```
yzguy@router.gru1:~$ show bgp vrf DN42 ipv4 neighbors fe80::2608 received-routes
<nothing>
yzguy@router.gru1:~$ show bgp vrf DN42 ipv6 neighbors fe80::2608 received-routes
BGP table version is 63372, local router ID is 172.20.19.72, vrf id 4
Default local pref 100, local AS 4242420207
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

    Network          Next Hop            Metric LocPrf Weight Path
 *> fd00:21:259e::/48
                    ::                                     0 4242422608 4242421816 4242422547 4242420293 i
 *> fd00:420:69::/48 ::                                     0 4242422608 4242421816 4242421588 4242423117 i
 *> fd00:1072:9982::/48
 ```

**Comment by Slirya** [comment]
use separate IPv4 and IPv6 sessions.

**Comment by yzguy** [comment]
@Slirya Deal, PR incoming to change it!

**Pull request merged**
