### PR TITLE
Add AS4242421022 peering at DAL1

### PR DESCRIPTION
**Pull request by bsdrocker**

### CODE REVIEW

**Review by jvoss — APPROVED** [review]

**Comment by bsdrocker** [comment]
Has this been provisioned on your side yet? I have not seen the tunnel or BGP come up on my side yet.

**Comment by jvoss** [comment]
Yes - your side does not appear to be responding:

```
router.dal1:~$ ping fe80::1022 vrf DN42 source-address fe80::207 interface wg4242421022
PING fe80::1022(fe80::1022) from fe80::207%wg4242421022 wg4242421022: 56 data bytes
^C
--- fe80::1022 ping statistics ---
12 packets transmitted, 0 received, 100% packet loss, time 11250ms
```

```
router.dal1:~$ sudo tcpdump -i wg4242421022
04:40:44.621793 IP6 fe80::207 > fe80::1022: ICMP6, echo request, id 5464, seq 1, length 64
04:40:45.677716 IP6 fe80::207 > fe80::1022: ICMP6, echo request, id 5464, seq 2, length 64
04:40:46.701704 IP6 fe80::207 > fe80::1022: ICMP6, echo request, id 5464, seq 3, length 64
04:40:47.725679 IP6 fe80::207 > fe80::1022: ICMP6, echo request, id 5464, seq 4, length 64
04:40:48.749779 IP6 fe80::207 > fe80::1022: ICMP6, echo request, id 5464, seq 5, length 64
04:41:12.747882 IP6 fe80::207.44349 > fe80::1022.bgp: Flags [S], seq 3312721579, win 65280, options [mss 1360,sackOK,TS val 3452667159 ecr 0,nop,wscale 7], length 0
04:41:13.773665 IP6 fe80::207.44349 > fe80::1022.bgp: Flags [S], seq 3312721579, win 65280, options [mss 1360,sackOK,TS val 3452668185 ecr 0,nop,wscale 7], length 0
```

Currently `dal-us-01.bsdrocker.com` resolves to an IPv6 address of `2600:3c00::f03c:95ff:fe7e:d0f4` which will be preferred over IPv4. Are you sure this is configured correctly?

```
router.dal1:~$ ping 2600:3c00::f03c:95ff:fe7e:d0f4
PING 2600:3c00::f03c:95ff:fe7e:d0f4(2600:3c00::f03c:95ff:fe7e:d0f4) 56 data bytes
From 2600:3c00::f03c:93ff:fe9d:2115 icmp_seq=1 Destination unreachable: Address unreachable
```

IPv4 (`dal-us-01.bsdrocker.com`):
```
router.dal1:~$ ping 173.255.200.199
PING 173.255.200.199 (173.255.200.199) 56(84) bytes of data.
64 bytes from 173.255.200.199: icmp_seq=1 ttl=59 time=0.524 ms
64 bytes from 173.255.200.199: icmp_seq=2 ttl=59 time=0.377 ms
64 bytes from 173.255.200.199: icmp_seq=3 ttl=59 time=0.398 ms
^C
--- 173.255.200.199 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2015ms
rtt min/avg/max/mdev = 0.377/0.433/0.524/0.064 ms
```

**Comment by bsdrocker** [comment]
Yeah, that is definitely the right address:

`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2600:3c00::f03c:95ff:fe7e:d0f4/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 5358sec preferred_lft 1758sec
    inet6 fe80::f03c:95ff:fe7e:d0f4/64 scope link
       valid_lft forever preferred_lft forever`

I can't ping your v6 address either:

`bsdrocker@dal-us-01:~$ ping 2600:3c00::f03c:93ff:fe9d:2115
PING 2600:3c00::f03c:93ff:fe9d:2115 (2600:3c00::f03c:93ff:fe9d:2115) 56 data bytes
^C
--- 2600:3c00::f03c:93ff:fe9d:2115 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7195ms

bsdrocker@dal-us-01:~$`

I'm also not seeing any return traffic from you in a tcpdump as well:

`bsdrocker@dal-us-01:~$ sudo tcpdump host 2600:3c00::f03c:93ff:fe9d:2115
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
16:15:45.057592 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:15:50.189004 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:15:55.308797 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:16:00.428657 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:16:06.060409 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:16:09.617332 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 1, length 64
16:16:10.668250 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 2, length 64
16:16:11.692557 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 3, length 64
16:16:11.692759 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
16:16:12.716295 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 4, length 64
16:16:13.740584 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 5, length 64
16:16:14.764586 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 6, length 64
16:16:15.788272 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 7, length 64
16:16:16.812729 IP6 dal-us-01 > router.dal1.routedbits.com: ICMP6, echo request, id 46548, seq 8, length 64
16:16:17.324400 IP6 dal-us-01.42207 > router.dal1.routedbits.com.51022: UDP, length 148
^C
15 packets captured
17 packets received by filter
0 packets dropped by kernel
bsdrocker@dal-us-01:~$`

I even went so far as to just allow everything coming from your v6 address:

`bsdrocker@dal-us-01:~$ sudo ufw status |grep 2600
Anywhere (v6)              ALLOW       2600:3c00::f03c:93ff:fe9d:2115
bsdrocker@dal-us-01:~$`

Is your VPS with Linode? I wonder if there is something on their side preventing this.

**Comment by bsdrocker** [comment]
I changed my wireguard config to just point to the v4 address of your router and it came up. I can ping fe80::207 now, but BGP isn't coming up. Any insights on your side?

**Comment by bsdrocker** [comment]
Here it is, pretty straight forward. I did have an issue at first with it not being able to open a socket but that was related to how I was configuring the Link Local address on my wireguard interface I believe. Those errors might have been related to that. I don't see those errors on my side, but BGP status is still stuck in Active.

> router bgp 4242421022
 neighbor fe80::207 remote-as 4242420207
 neighbor fe80::207 capability extended-nexthop
 !
 address-family ipv4 unicast
  neighbor fe80::207 next-hop-self
  neighbor fe80::207 route-map dn42_v4_in in
  neighbor fe80::207 route-map dn42_v4_out out
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fe80::207 activate
  neighbor fe80::207 next-hop-self
  neighbor fe80::207 route-map dn42_v6_in in
  neighbor fe80::207 route-map dn42_v6_out out
 exit-address-family
 !
exit
!

**Comment by jvoss** [comment]
When using link-local addressing you will need to assign the neighbor to an update interface:

```
router bgp 4242421022
  neighbor fe80::207 interface <wireguard interface name here>
  neighbor fe80::207 update-source fe80::1022
```

Link-local is just that, local to the link, such that those addresses can (and do) overlap. The system will require some way to uniquely identify which interface to use.

**Comment by bsdrocker** [comment]
OK, well I'm at a loss because I did that and it still doesn't work. Am I setting up the wireguard interface incorrectly?

```
bsdrocker@dal-us-01:~$ sudo cat /etc/wireguard/wg1.conf
[Interface]
PrivateKey = ***********************
ListenPort = 42207
Address = fe80::1022/128
PostUp = ip address add dev %i peer fe80::207
Table = off

[Peer]
PublicKey = 8clbJPxK5ylOhFDNGdn/CL5zRWQdf7rXbLeF7j8czFI=
Endpoint = 104.200.19.98:51022
AllowedIPs = 172.20.0.0/14, fd00::/8, fe80::207/128
```

**Comment by jvoss** [comment]
Can you send me the output from `show bgp neighbors fe80::207`?

I suspect you also do not have a router ID set. Some implementations will automatically pick the highest IPv4 address assigned to an interface, however I'm guessing you are using FRR? FRR will require you to set a router-id if you have no IPv4 BGP neighbors for it to pick an address from. 

In any case, I would consider it best practice to configure a static router-id. It does not have to be a real IPv4 address in use but it must be unique between you and your neighbors. You could do something like like this:

```
router bgp 4242421022
  bgp router-id 172.22.240.64
```

**Comment by bsdrocker** [comment]
I do have a router-id set, still nada. Looking at the show bgp neighbors it definitely seems like something is a miss since it isn't even showing any Sent counters:

```
dal-us-01# show bgp neighbors fe80::207
BGP neighbor is fe80::207, remote AS 4242420207, local AS 4242421022, external link
  Local Role: undefined
  Remote Role: undefined
  BGP version 4, remote router ID 0.0.0.0, local router ID 172.22.240.64
  BGP state = Active
  Last read 00:37:54, Last write never
  Hold time is 180 seconds, keepalive interval is 60 seconds
  Configured hold time is 180 seconds, keepalive interval is 60 seconds
  Configured conditional advertisements interval is 60 seconds
  Graceful restart information:
    Local GR Mode: Helper*
    Remote GR Mode: NotApplicable
    R bit: False
    N bit: False
    Timers:
      Configured Restart Time(sec): 120
      Received Restart Time(sec): 0
  Message statistics:
    Inq depth is 0
    Outq depth is 0
                         Sent       Rcvd
    Opens:                  0          0
    Notifications:          0          0
    Updates:                0          0
    Keepalives:             0          0
    Route Refresh:          0          0
    Capability:             0          0
    Total:                  0          0
  Minimum time between advertisement runs is 0 seconds
  Update source is wg1

 For address family: IPv4 Unicast
  Not part of any update group
  NEXT_HOP is always this router
  Community attribute sent to this neighbor(all)
  Inbound updates discarded due to missing policy
  Outbound updates discarded due to missing policy
  0 accepted prefixes

 For address family: IPv6 Unicast
  Not part of any update group
  Community attribute sent to this neighbor(all)
  Inbound updates discarded due to missing policy
  Outbound updates discarded due to missing policy
  0 accepted prefixes

  Connections established 0; dropped 0
  Last reset 00:37:54,  Waiting for NHT
  External BGP neighbor may be up to 1 hops away.
BGP Connect Retry Timer in Seconds: 120
Next connect timer due in 10 seconds
Read thread: off  Write thread: off  FD used: -1
```

**Comment by jvoss** [comment]
I think you changed something with your WireGuard configuration. We are now unable to ping your tunnel endpoint:

```
router.dal1:~$ ping fe80::1022 vrf DN42 source-address fe80::207 interface wg4242421022
PING fe80::1022(fe80::1022) from fe80::207%wg4242421022 wg4242421022: 56 data bytes
^C
--- fe80::1022 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7187ms
```

**Comment by bsdrocker** [comment]
Can you now? I undid what I had done. I believe the issue is my FRR is not resolving the next-hop for the link-local address:

```
dal-us-01# sho ipv6 nht fe80::207
dal-us-01#
```

**Comment by jvoss** [comment]
Nope... do you have a firewall involved here? Is it blocking `UDP/42207` or `UDP/51022`

```
router.dal1:~$ tcpdump -i eth0 port 42207
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
18:40:56.774374 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 112
18:41:21.985962 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 144
18:41:23.014323 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 144
18:41:24.038297 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 144
18:41:25.062304 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 144
18:41:26.086299 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 144
```

FRR is not going to matter at all if the underlying connectivity is not working first :)

**Comment by bsdrocker** [comment]
Works for me:

```
bsdrocker@dal-us-01:~$ sudo tcpdump -i eth0 port 42207
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
18:50:34.796301 IP 173-255-200-199.ip.linodeusercontent.com.42207 > router.dal1.routedbits.com.51022: UDP, length 32
18:50:56.845587 IP router.dal1.routedbits.com.51022 > 173-255-200-199.ip.linodeusercontent.com.42207: UDP, length 112
18:51:07.052368 IP 173-255-200-199.ip.linodeusercontent.com.42207 > router.dal1.routedbits.com.51022: UDP, length 32
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel
bsdrocker@dal-us-01:~$ ping fe80::207
PING fe80::207 (fe80::207) 56 data bytes
64 bytes from fe80::207%wg1: icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from fe80::207%wg1: icmp_seq=2 ttl=64 time=0.051 ms
^C
--- fe80::207 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1031ms
rtt min/avg/max/mdev = 0.038/0.044/0.051/0.006 ms
bsdrocker@dal-us-01:~$
```

I'm to the point of just moving this to ULA v6 addressing and calling it a day. I can resubmit a PR. Thoughts?

**Comment by jvoss** [comment]
IPv6 ULA can be used if you want, we support it on our end. It's going to be difficult for me to troubleshoot your situation by without seeing everything myself though, as well as there may be multiple issues going on with your configuration.

I would caution that without being able to prove basic connectivity between us, nothing in FRR is going to matter (yet):
```
router.dal1:~$ tcpdump -i wg4242421022
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on wg4242421022, link-type RAW (Raw IP), snapshot length 262144 bytes
19:02:40.422951 IP6 fe80::207.48366 > fe80::1022.bgp: Flags [S], seq 1922356347, win 65280, options [mss 1360,sackOK,TS val 3100426645 ecr 0,nop,wscale 7], length 0
19:02:41.478243 IP6 fe80::207.48366 > fe80::1022.bgp: Flags [S], seq 1922356347, win 65280, options [mss 1360,sackOK,TS val 3100427701 ecr 0,nop,wscale 7], length 0
19:02:42.502256 IP6 fe80::207.48366 > fe80::1022.bgp: Flags [S], seq 1922356347, win 65280, options [mss 1360,sackOK,TS val 3100428725 ecr 0,nop,wscale 7], length 0
```
The above shows that we receive no response when attempting to open a TCP connection with you on port 179 (BGP). This may be indicative of some kind of firewall issue on your end perhaps? We have numerous neighbors that peer at this location using this type of configuration without issue.

If another deployment method is easier or more familiar to you, then you might try that. Update the peering for us to use an IPv4 destination on your side since we know there is questionable connectivity over IPv6 between us.

**Comment by bsdrocker** [comment]
OK - there might be an issue with my UFW config, which I'll dig in to later - its disabled on the moment. I'm seeing the peering trying to come up now. Here are the logs I'm seeing. It fails with an "OPEN Message Error/Unsupported Capability" message.

```
2024-11-22 19:43:55.936 [DEBG] bgpd: [ZQHFG-DQGX1] fe80::207 went from Idle to Active
2024-11-22 19:43:55.936 [DEBG] bgpd: [ZWCSR-M7FG9] fe80::207 [FSM] TCP_connection_open (Active->OpenSent), fd 28
2024-11-22 19:43:55.936 [DEBG] bgpd: [WECS1-Q4P17] fe80::207 passive open
2024-11-22 19:43:55.936 [DEBG] bgpd: [XKJ09-9VTZ7] fe80::207 Sending hostname cap with hn = dal-us-01, dn = (null)
2024-11-22 19:43:55.936 [DEBG] bgpd: [JFFAN-DEGED] fe80::207 sending OPEN, version 4, my as 4242421022, holdtime 180, id 172.22.240.64
2024-11-22 19:43:55.936 [DEBG] bgpd: [T91AW-FGMHW] bgp_fsm_change_status : vrf default(0), Status: OpenSent established_peers 2
2024-11-22 19:43:55.936 [DEBG] bgpd: [ZQHFG-DQGX1] fe80::207 went from Active to OpenSent
2024-11-22 19:43:55.937 [DEBG] bgpd: [WNM1E-D314G] fe80::207 rcv OPEN, version 4, remote-as (in open) 23456, holdtime 180, id 172.20.19.68
2024-11-22 19:43:55.937 [DEBG] bgpd: [QG29C-5TSVS] fe80::207 rcv OPEN w/ OPTION parameter len: 99
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 6
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has MultiProtocol Extensions capability (1), length 4
2024-11-22 19:43:55.937 [DEBG] bgpd: [VXVH9-3MXR0] fe80::207 OPEN has MultiProtocol Extensions capability for afi/safi: IPv4/unicast
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 8
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has Extended Next Hop Encoding capability (5), length 6
2024-11-22 19:43:55.937 [DEBG] bgpd: [XCS8V-P66M1] fe80::207 Received with afi/safi/next-hop afi: IPv4/unicast/2
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 6
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has MultiProtocol Extensions capability (1), length 4
2024-11-22 19:43:55.937 [DEBG] bgpd: [VXVH9-3MXR0] fe80::207 OPEN has MultiProtocol Extensions capability for afi/safi: IPv6/unicast
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 2
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has Route Refresh capability (2), length 0
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 2
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has Enhanced Route Refresh capability (70), length 0
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 6
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has 4-octet AS number capability (65), length 4
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 2
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has BGP Extended Message capability (6), length 0
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 10
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has AddPath capability (69), length 8
2024-11-22 19:43:55.937 [DEBG] bgpd: [SBSKM-G6QBW] fe80::207 OPEN has AddPath capability for afi/safi: IPv4/unicast, receive
2024-11-22 19:43:55.937 [DEBG] bgpd: [SBSKM-G6QBW] fe80::207 OPEN has AddPath capability for afi/safi: IPv6/unicast, receive
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 15
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has FQDN capability (73), length 13
2024-11-22 19:43:55.937 [DEBG] bgpd: [MR6EG-NS6N7] fe80::207 received hostname router.dal1, domainname (null)
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 4
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has Graceful Restart capability (64), length 2
2024-11-22 19:43:55.937 [DEBG] bgpd: [KDY57-R1CN0] fe80::207 Peer has not restarted. Restart Time: 120, N-bit set: yes
2024-11-22 19:43:55.937 [DEBG] bgpd: [NVZPF-5ST3B] fe80::207 rcvd OPEN w/ optional parameter type 2 (Capability) len 16
2024-11-22 19:43:55.937 [DEBG] bgpd: [SCW43-WN4M1] fe80::207 OPEN has Long-lived BGP Graceful Restart capability (71), length 14
2024-11-22 19:43:55.937 [DEBG] bgpd: [ZVHDJ-HW40B] fe80::207 Addr-family IPv4/unicast(afi/safi) not enabled. Ignore the Long-lived Graceful Restart capability
2024-11-22 19:43:55.938 [DEBG] bgpd: [ZVHDJ-HW40B] fe80::207 Addr-family IPv6/unicast(afi/safi) not enabled. Ignore the Long-lived Graceful Restart capability
2024-11-22 19:43:55.938 [DEBG] bgpd: [ZWCSR-M7FG9] fe80::207 [FSM] Receive_OPEN_message (OpenSent->OpenConfirm), fd 28
2024-11-22 19:43:55.938 [DEBG] bgpd: [T91AW-FGMHW] bgp_fsm_change_status : vrf default(0), Status: OpenConfirm established_peers 2
2024-11-22 19:43:55.938 [DEBG] bgpd: [ZQHFG-DQGX1] fe80::207 went from OpenSent to OpenConfirm
2024-11-22 19:43:55.938 [INFO] bgpd: [HZN6M-XRM1G] %NOTIFICATION: received from neighbor fe80::207 2/7 (OPEN Message Error/Unsupported Capability) 2 bytes 80 00
```

**Comment by jvoss** [comment]
Is your autonomous-system number configured correctly?

```
Notification sent (OPEN Message Error/Bad Peer AS)
```

We are expecting: `4242421022`

**Comment by jvoss** [comment]
Looks like your ASN has been corrected... There are a few capabilities here that may be causing problems.

The most glaring one I see first off is support for dynamic capabilities. This is not enabled by default in our implementation and we don't currently support this. It should be disabled with:

```
router bgp 4242421022
  no neighbor fe80::207 capability dynamic
```

What version of FRR are you running?

**Comment by bsdrocker** [comment]
8.4.4 it looks like. Installed via apt on Ubuntu Server 24.04.1. Digging in to the OPEN error message code, its a type 2 which still indicates Bad Peer AS according to the BGP RFC. I have your neighbor set to:

```
neighbor fe80::207 remote-as 4242420207
```

Which should be right...

**Comment by jvoss** [comment]
Yes - it appears you resolved that.. please read my latest response after that: https://github.com/routedbits/dn42-peers/pull/216#issuecomment-2494766817

**Pull request merged**
