### PR TITLE
Update router.mil1.yml

### PR DESCRIPTION
**Pull request by kolobus**
Totally failed to make Mikrotik RouterOS to use link-local address I want it to use.
Would like to have different set of addresses to unify peers logic.

### CODE REVIEW

**Comment by yzguy** [comment]
@kolobus Please take a look at the validation error. The IPv4/6 IP you use should be from your DN42 allocation

**Comment by kolobus** [comment]
Mikrotik config is a bit ugly. I can not assign same subnet address to WireGurad interface, other peer WireGuard interface and real internal interface. WireGuard address must be this specific. Can it be used with you?

**Comment by kolobus** [comment]
Nevermind, I'll try to figure out different workaround.
PR is now correct and can be merged. Thanks!

**Comment by kolobus** [comment]
Is this node (mil1) actually alive?

Screenshot 2024-10-02 at 7 21 32

**Pull request merged**
